import type { Metadata } from "next";
import { Outfit, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import MyPage from "./_app";
const outfit = Outfit({ subsets: ["latin"] });
const spaceGortesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorPrimary: "white",
          colorText: "white",
          colorTextSecondary: "grey",
          colorBackground: "black",
          fontSize: "text-2xl",
        },
      }}
    >
      <html lang="en" className="!scroll-smooth overflow-y-scroll no-scrollbar">
        <MyPage />
        <body className={spaceGortesk.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
